name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag levit8au/azuread-ldap-wrapper:${{ github.sha }}
    - name: Docker Push
      run: docker push levit8au/azure-ad-ldap-wrapper:${{ github.sha }}
    - name: docker logout
      run: docker logout
